### ISSUE TITLE
android example

### ISSUE THREAD

**Issue by INHack20** [CrossGeeks/MultilingualXFSample#1]
The example does not work on android.

**Comment by Char0394** [comment]
I did a commit this morning, did you check it?

**Comment by INHack20** [comment]
Yes, I just cloned the example a few minutes ago and I tested it on android 5.0 and it doesn't change the language.

**Comment by Char0394** [comment]
Ok, I Will check it.
Did you test in a physical device or android simulator?
Also, which android are you using to test?

**Comment by INHack20** [comment]
@Char0394 
Android simulator.
In Android 6.0 and Android 9.0

Thanks

**Comment by Char0394** [comment]
Cold you try in a physical device please?

**Comment by INHack20** [comment]
@Char0394  In a physical device with android 9.0 it works perfectly.
The problem is with emulators.

**Comment by plucenio** [comment]
Hi! I have a problem with a physical device. I'm working to solve the problem too.

**Comment by joseluisct** [comment]
Hi, I have the same problem on Android physical device: Samsung Galaxy Note 8 with Android 9, the text it's always in English

**Comment by ufukhawk** [comment]
Hi, Android doesn't work on both physical devices and emulators.

**Comment by plucenio** [comment]
The problem started for me after the last visual studio (MAC) update (Version 8.6 (build 4520)). A coincidence or someone with the same?

**Comment by ufukhawk** [comment]
@plucenio Yes, After using the Multilingual Plugin in vs for mac after the last update, "System.Resources.MissingManifestResourceException" error is received.

And this plugin will no longer be supported. therefore I uninstalled this Multilingual Plugin and did not implement this recommended new method. It works great on iOS devices but it didn't work on any of the android devices.

**Comment by ufukhawk** [comment]
Hey!, solved my problem, https://github.com/xamarin/xamarin-android/issues/4664#issuecomment-632986668 
The problem is not in the code.
In the visual studio for mac version.

**Comment by Char0394** [comment]
Hi, 
Just tested in some simulators and you guys were right it is not working.

I did the @ufukhawk workaround and it is working now. (Just pushed the changes in the repo, so you can pull the latest changes and test back again).

Thanks, @ufukhawk :)

**Comment by ufukhawk** [comment]
Hi, Last Stable version for VS for MAC(8.6.1(build 26) The problem has been fixed.
Please remove workaround.

**Comment by Char0394** [comment]
Great! Thanks for letting us know!

**Comment by MobilyteApps** [comment]
> Hi, I have the same problem on Android physical device: Samsung Galaxy Note 8 with Android 9, the text it's always in English
----
Hi Have you fixes in android ?

**Comment by MobilyteApps** [comment]
> The example does not work on android.

Hey, Your code is working in Android ?

**Comment by Char0394** [comment]
@MobilyteApps yes, it is working on Android!

**Comment by MobilyteApps** [comment]
@Char0394 :- I do not know what i missed, because there is nothing in code level only create a resource and set the resources 

Below are our code:- 
----------------------------
item.code is 

 new Item { Title = "Española".ToString(), Code = "es-pr", IsSelected=true },
 new Item { Title = "English".ToString(), Code = "en-gb", IsSelected=false }

CrossMultilingual.Current.CurrentCultureInfo = new System.Globalization.CultureInfo(item.Code);
 AppResources.Culture = CrossMultilingual.Current.CurrentCultureInfo;

and Resource file is attached
[Resources.zip](https://github.com/CrossGeeks/MultilingualXFSample/files/4698644/Resources.zip)

The code is previously working in VS 16.3.2 but when i updated to VS 16.6 Windows, its giving problem.

if you find problem, please let me know..

Thanks

**Comment by Char0394** [comment]
The issue is with visual studio not with the code. 
Check this ticket: https://github.com/xamarin/xamarin-android/issues/4664#issuecomment-632986668
